[package]

name = "piston_window"
version = "0.54.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["window", "piston"]
description = "The official Piston window wrapper for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/piston_window.git"
homepage = "https://github.com/pistondevelopers/piston_window"
documentation = "http://docs.piston.rs/piston_window/piston_window/"

[lib]

path = "src/lib.rs"
name = "piston_window"


[dependencies]
gfx = "0.12.0"
gfx_core = "0.4.0"
gfx_device_gl = "0.11.0"
#piston = "0.25.0"
#piston = {path = 'D:\projects\forks\piston'}
piston = {git = 'https://github.com/Boscop/piston'}
piston2d-gfx_graphics = "0.31.1"
piston2d-graphics = "0.17.0"
piston-texture = "0.5.0"
shader_version = "0.2.0"
#pistoncore-glutin_window = "0.30.0"
#pistoncore-glutin_window = {path = 'D:\projects\forks\glutin_window'}
pistoncore-glutin_window = {git = 'https://github.com/Boscop/glutin_window'}
